modLoader="javafml" #mandatory

loaderVersion="[2,)" #mandatory

license="All Rights Reserved"

[[mods]] #mandatory

modId="mcjjkp" #mandatory
version="0.0.1" #mandatory
displayName="JJKProject" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="MCGamer" #optional
description='''${mod_description}'''

[[mixins]]
config="mcjjkp.mixins.json"

[[accessTransformers]]
file="accesstransformer_main.cfg"

[[accessTransformers]]
file="recipebuilders.cfg"

[[accessTransformers]]
file="blockproperties.cfg"

[[accessTransformers]]
file="renderstates.cfg"

[[dependencies.mcjjkp]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcjjkp]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcjjkp]]
    modId="curios"
    type="required"
    versionRange="[9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcjjkp]]
    modId="lodestone"
    type="required"
    versionRange="[1.7.2,)"
    ordering="NONE"
    side="BOTH"


#[features.${mod_id}]
#openGLVersion="[3.2,)"
